name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Change 'main' to your branch name if different

permissions:
  contents: write   # Allows write access to repository contents (important for pushing to gh-pages)
  pages: write      # Allows writing to GitHub Pages
  id-token: write   # (Optional) Required for some specific use cases      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.0' # Use the Node.js version compatible with your app

      - name: Navigating to frontend
        run: cd my-portfolio

      - name: Install dependencies
        run: cd my-portfolio
             npm install

      - name: Build the app
        run: cd my-portfolio
             npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: my-portfolio/dist
          publish_branch: gh-pages
